config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'shipping#index'
	get 'my_profile', to: 'users#my_profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def index

end

end

app/controllers/shipping_controller.rb
class ShippingController < ApplicationController


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def my_profile

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shipping_helper.rb
module ShippingHelper
end

app/views/layouts/_error.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <%= link_to 'Versand', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <% if current_user %>
                <%= link_to 'My Profile', my_profile_path, class: "nav-link" %>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
            <ul class= 'navbar-nav ml-auto'>
              <li class='nav-item'>
                <%= link_to("Logout", destroy_user_session_path,
                class: "btn btn-danger logout-button", method: :delete) %>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
          <% else %>
          <li>
           <%= link_to 'Signin', user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to 'Signup', new_user_registration_path, class: "nav-link" %> 
          </li>
        <% end %>
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Versand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/error' %>
    <%= yield %>
  </body>
</html>

app/views/shipping/_ship_quote.html.erb
<div class="container d-flex justify-content-center">

		<div class="row">
			<div class="col-xs-6 ultra-padding">
			
			<%= render 'shipping/location_form', key:"Shipping From" %>
			</div>

			<div class="col-xs-6 ultra-padding">
				
				<%= render 'shipping/location_form', key:"Shipping To" %>
			</div>
		</div>
</div>

<div class="container d-flex justify-content-center">
<button type="submit" class="btn btn-primary btn-space" style="width: 8rem;">Check Rates</button>
</div>

app/views/shipping/index.html.erb
<div class="container">
	<div class="jumbotron text-center">
	  <div class="container">
	    <h1 class="display-4">See Your Savings Today!</h1>
	    <p class="lead">Compare your current rates with our reduced rates and start saving today</p>
	  </div>
	</div>
</div>


<%= render 'shipping/ship_quote' %>

app/views/users/my_profile.html.erb
<h1>My Profile</h1>